apiVersion : apps/v1
kind: Deployment
metadata:
  name: myy-deployment
  labels:
    app : myy-app
spec:
  replicas: 3  # 3 Pods
  selector:
    matchLabels:
      project: gksb  # селектор зв'язки Deployment з Pod
  template: # робота з Pod
    metadata:
      labels:
        project: gksb # зв'язка Pod з Deployment та Service
    spec:
      containers:
      - name: gksb-container
        image: nstsn/docker_app:latest
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: my-pood-service
  labels:
    env: prod
    owner: AnSk
spec:
  selector:
    project: gksb # обираємо Pods з цим label
  ports:
    - name: app-listeneer
      protocol: TCP
      port: 80 # on LoadBalancer
      targetPort: 80 # on Pod
  type: LoadBalancer
