name: CI/CD


on: 
  push:
     branches:
         - main
  pull_request:
     branches: 
         - main


jobs:
   linting:
   
       runs-on: ubuntu-latest
       
       steps:
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
          node-version: ${{ env.NODE_VERSION }}
       - name: Install eslint
         run: npm i eslint
       - name: Eslint checks
         run: node_modules/eslint/bin/eslint.js 
       
   build-image:
   
       runs-on: ubuntu-latest
       needs: linting
       
       steps:
       - name: Check out
         uses: actions/checkout@v3
       - name: Setup Docker
         uses: docker/setup-buildx-action@v2
       - name: Build image
         run: docker build -t nstsn/docker_app:latest .

   push-image:
   
       runs-on: ubuntu-latest
       needs: build-image
       
       steps:
       - name: Check out
         uses: actions/checkout@v3
       - name: Login
         uses: docker/login-action@v2
         with:
          username: nstsn
          password: ${{ secrets.DOCKER_PASSWORD }}
