name: CI/CD


on: 
  push:
     branches:
         - main


jobs:
   linting:
   
       runs-on: ubuntu-latest
       
       steps:
       - name: Setup Node.js
         uses: actions/setup-node@v2
         with:
          node-version: ${{ env.NODE_VERSION }}
       - name: Install eslint
         run: npm i eslint
       - name: Eslint checks
         run: node_modules/eslint/bin/eslint.js 
       
   build-image:
   
       runs-on: ubuntu-latest
       needs: linting
       
       steps:
       - name: Check out
         uses: actions/checkout@v3
       


   push-image:
   
       runs-on: ubuntu-latest
       needs: build-image
       
       steps:
       - name: Check out
         uses: actions/checkout@v3
